module.exports = (sequelize, DataTypes) => {

    const Partner = sequelize.define("partner", {
        id: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            autoIncrement: true,
            primaryKey: true
        },
        partnerId: {
            type: DataTypes.STRING(100),
            allowNull: false,
            unique: true,
            comment: "Unique partner identifier (generated by T2Mobile)"
        },
        companyName: {
            type: DataTypes.STRING(255),
            allowNull: false
        },
        tier: {
            type: DataTypes.ENUM('GOLD', 'SILVER', 'BRONZE'),
            defaultValue: 'BRONZE'
        },
        revenueShare: {
            type: DataTypes.DECIMAL(5, 4),
            defaultValue: 0.30,
            comment: "Revenue share percentage (e.g., 0.30 for 30%)"
        },
        status: {
            type: DataTypes.ENUM('ACTIVE', 'INACTIVE'),
            defaultValue: 'ACTIVE'
        },
        apiBaseUrl: {
            type: DataTypes.STRING(500),
            allowNull: true
        },
        apiKey: {
            type: DataTypes.STRING(500),
            allowNull: true,
            comment: "Encrypted API key"
        },
        webhookSecret: {
            type: DataTypes.STRING(500),
            allowNull: true,
            comment: "Encrypted webhook secret"
        },
        contactEmail: {
            type: DataTypes.STRING(255),
            allowNull: true
        },
        contactPhone: {
            type: DataTypes.STRING(50),
            allowNull: true
        },
        description: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        metadata: {
            type: DataTypes.JSON,
            allowNull: true
        },
        createdAt: {
            type: DataTypes.DATE,
            defaultValue: DataTypes.NOW
        },
        updatedAt: {
            type: DataTypes.DATE,
            defaultValue: DataTypes.NOW
        }
    }, {
        indexes: [
            {
                fields: ['partnerId']
            },
            {
                fields: ['status']
            }
        ]
    });

    return Partner;
};